const UPLOADS='/images/uploads/';
const RAW='https://raw.githubusercontent.com/Holkarandasshemraj/Holkarandasshemraj.github.io/main/images/uploads/';
const CONTENT='content.yml';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fallback={
 shop_name:'Holkaran Dass Hem Raj',tagline:'Learn. Create. Play. Celebrate.',logo:UPLOADS+'file_00000000f9e48211ae9421db860baf41.png',
 navigation:{home_label:'Home',shop_label:'Shop',all_categories_label:'All Categories',brands_label:'Brands',all_brands_label:'All Brands',products_label:'Products',about_label:'About',gallery_label:'Gallery',contact_label:'Contact'},
 hero_images:[
  {image:UPLOADS+'sandy-millar-s5pfhdxuxyw-unsplash.jpg',heading:'Books for Every Interest',text:'Educational, academic, story and general reading books for all ages.',show:true,show_button:true,button_text:'View Books',button_link:'products.html?category=Books',show_second_button:true,second_button_text:'Visit Our Store',second_button_link:'contact.html'},
  {image:UPLOADS+'hannah-rodrigo-mf_3yznc6ug-unsplash.jpg',heading:'Stationery for Everyday Needs',text:'School, office, art and writing essentials in one convenient place.',show:true,show_button:true,button_text:'Shop Stationery',button_link:'products.html?category=Stationery',show_second_button:true,second_button_text:'Visit Our Store',second_button_link:'contact.html'},
  {image:UPLOADS+'caroline-6f-dcqhdqnu-unsplash.jpg',heading:'Gifts, Toys & More',text:'Fun and thoughtful choices for birthdays, celebrations and special moments.',show:true,show_button:true,button_text:'Explore More',button_link:'products.html',show_second_button:true,second_button_text:'Visit Our Store',second_button_link:'contact.html'},
  {image:UPLOADS+'declan-sun-fkjgygsjtko-unsplash.jpg',heading:'Learn. Create. Play.',text:'Science goods and sports essentials for curious and active minds.',show:true,show_button:true,button_text:'Enquire Now',button_link:'contact.html',show_second_button:true,second_button_text:'Visit Our Store',second_button_link:'contact.html'}
 ],
 categories:[{name:'Stationery',icon:'✏️',show:true},{name:'Books',icon:'📚',show:true},{name:'Sports',icon:'⚽',show:true},{name:'Gifts',icon:'🎁',show:true},{name:'Toys',icon:'🧸',show:true},{name:'Science Goods',icon:'🔬',show:true}],
 brands:[{name:'Classmate',description:'Stationery and school essentials.',show:true},{name:'Camlin',description:'Art, writing and stationery products.',show:true},{name:'Faber-Castell',description:'Writing and creative products.',show:true},{name:'DOMS',description:'Stationery, art and school products.',show:true},{name:'Staedtler',description:'Writing, drawing and school products.',show:true},{name:'Nataraj',description:'Everyday writing and stationery products.',show:true}],
 products:[{name:'Books',category:'Books',description:'Explore books for students, children and readers of all ages.',show:true},{name:'Stationery',category:'Stationery',description:'Notebooks, pens, pencils, school supplies, art materials and more.',show:true},{name:'Sports',category:'Sports',description:'Sports products and accessories for students and enthusiasts.',show:true},{name:'Science Goods',category:'Science Goods',description:'Educational products for projects, experiments and practical learning.',show:true},{name:'Gifts',category:'Gifts',description:'Thoughtful gifts for birthdays, celebrations and special moments.',show:true},{name:'Toys',category:'Toys',description:'Fun, creative and educational toys for children.',show:true}],
 about_title:'About Our Store',about_text:'Welcome to Holkaran Dass Hem Raj — your trusted destination for books, stationery, gifts, toys, science goods, and sports essentials.\n\nWe bring together quality products for learning, creativity, fun, and everyday needs, all under one roof.\n\nVisit us and discover something for every age, every interest, and every occasion.',
 why_choose_us:[{icon:'🏪',title:'Wide Range',description:'Books, stationery, gifts, toys, science goods and sports products under one roof.',show:true},{icon:'🎯',title:'For Every Need',description:'Products for students, families, children and everyday requirements.',show:true},{icon:'📞',title:'Convenient Shopping',description:'Find what you need easily and contact us directly for enquiries.',show:true}],
 phone:'8053721234',whatsapp:'918053721234'
};
let data=JSON.parse(JSON.stringify(fallback));
function imageUrl(v){if(!v)return '';v=String(v);if(v.startsWith('data:')||v.startsWith('blob:'))return v;if(/^https?:\/\//i.test(v)){const m=v.match(/\/images\/uploads\/(.+)$/);return m?RAW+m[1]:v}if(v.startsWith('/images/uploads/'))return RAW+v.substring('/images/uploads/'.length);return UPLOADS+v.split('/').pop()}
async function loadData(){try{const r=await fetch(CONTENT+'?v='+Date.now(),{cache:'no-store'});if(r.ok&&window.jsyaml){const parsed=jsyaml.load(await r.text());if(parsed&&typeof parsed==='object')data=Object.assign(data,parsed)}}catch(e){console.warn('Using fallback site content',e)}applyTheme();renderHeader();renderPage();}
function setVar(name,value){if(value!==undefined&&value!==null&&value!=='')document.documentElement.style.setProperty(name,value)}
function applyTheme(){const m={primary_color:'--primary',secondary_color:'--secondary',accent_color:'--accent',background_color:'--bg',card_background_color:'--card',text_color:'--text',heading_color:'--heading',call_button_color:'--call',enquire_button_color:'--enquire',button_text_color:'--btntext',font_family:'--bodyfont',heading_font:'--headingfont',nav_font:'--navfont',button_font:'--buttonfont',product_title_font:'--productfont',product_description_font:'--productdescfont',body_font_weight:'--bodyweight',heading_font_weight:'--headingweight',nav_font_weight:'--navweight',button_font_weight:'--buttonweight',product_title_font_weight:'--productweight',product_description_font_weight:'--productdescweight',body_font_style:'--bodystyle',heading_font_style:'--headingstyle',nav_font_style:'--navstyle',button_font_style:'--buttonstyle',product_title_font_style:'--productstyle',product_description_font_style:'--productdescstyle',hero_heading_font:'--heroheadingfont',hero_heading_font_weight:'--heroheadingweight',hero_heading_font_style:'--heroheadingstyle',hero_text_font:'--herotextfont',hero_text_font_weight:'--herotextweight',hero_text_font_style:'--herotextstyle',section_heading_font:'--sectionheadingfont',section_heading_font_weight:'--sectionheadingweight',section_heading_font_style:'--sectionheadingstyle',hero_heading_color:'--heroheadingcolor',hero_text_color:'--herotextcolor',section_heading_color:'--sectionheadingcolor',categories_heading_color:'--categoriesheadingcolor',products_heading_color:'--productsheadingcolor',brands_heading_color:'--brandsheadingcolor',why_heading_color:'--whyheadingcolor',about_heading_color:'--aboutheadingcolor',contact_heading_color:'--contactheadingcolor',body_size:'--bodysize',heading_size:'--headingsize',button_size:'--buttonsize',product_title_size:'--productsize',product_description_size:'--productdescsize'};Object.keys(m).forEach(k=>setVar(m[k],data[k]))}
function renderHeader(){document.querySelectorAll('[data-shop-name]').forEach(e=>e.textContent=data.shop_name||fallback.shop_name);document.querySelectorAll('[data-tagline]').forEach(e=>e.textContent=data.tagline||'');const logo=$('brandLogo');if(logo)logo.src=imageUrl(data.logo||fallback.logo);buildNavigation()}
function buildNavigation(){const nav=document.querySelector('.nav-list');if(!nav)return;const n=data.navigation||{};const cats=(data.categories||[]).filter(x=>x&&x.show!==false&&x.name);const brands=(data.brands||[]).filter(x=>x&&x.show!==false&&x.name);nav.innerHTML=`<li class="nav-item"><a class="nav-link" href="index.html">${esc(n.home_label||'Home')}</a></li><li class="nav-item has-dropdown"><button type="button" class="nav-link dropdown-toggle">${esc(n.shop_label||'Shop')} <span class="arrow">▾</span></button><div class="dropdown"><a href="categories.html">${esc(n.all_categories_label||'All Categories')}</a><a href="products.html">${esc(n.products_label||'All Products')}</a>${cats.map(c=>`<a href="products.html?category=${encodeURIComponent(c.name)}">${esc(c.name)}</a>`).join('')}</div></li><li class="nav-item has-dropdown"><button type="button" class="nav-link dropdown-toggle">${esc(n.brands_label||'Brands')} <span class="arrow">▾</span></button><div class="dropdown"><a href="brands.html">${esc(n.all_brands_label||'All Brands')}</a>${brands.map(b=>`<a href="products.html?brand=${encodeURIComponent(b.name)}">${esc(b.name)}</a>`).join('')}</div></li><li class="nav-item has-dropdown"><button type="button" class="nav-link dropdown-toggle">${esc(n.about_label||'About')} <span class="arrow">▾</span></button><div class="dropdown"><a href="about.html">${esc(n.about_label||'About Us')}</a><a href="gallery.html">${esc(n.gallery_label||'Gallery')}</a></div></li><li class="nav-item"><a class="nav-link" href="contact.html">${esc(n.contact_label||'Contact')}</a></li>`}
function setupNav(){const menu=$('menu'),nav=$('nav');if(menu&&nav)menu.onclick=()=>nav.classList.toggle('open');document.querySelectorAll('.dropdown-toggle').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const item=b.parentElement;document.querySelectorAll('.nav-item.has-dropdown.open').forEach(x=>x!==item&&x.classList.remove('open'));item.classList.toggle('open')})}
function renderPage(){const p=document.body.dataset.page||'home';if(p==='home')renderHome();else if(p==='categories')renderCategories();else if(p==='products')renderProducts();else if(p==='brands')renderBrands();else if(p==='about')renderAbout();else if(p==='gallery')renderGallery();else if(p==='contact')renderContact();setupNav()}
function renderHome(){renderHomeHero();renderHomeCategories();renderHomeProducts();renderHomeBrands();renderHomeWhy();renderHomeAbout();applySectionHeadingColors();toggleSection('show_categories','categoriesGrid');toggleSection('show_products','productsGrid');toggleSection('show_brands','homeBrands');toggleSection('show_why_choose_us','whyGrid');toggleSection('show_about','aboutText')}
function applySectionHeadingColors(){const set=(selector,key)=>{const color=data[key]||data.section_heading_color||data.heading_color;if(color)document.querySelectorAll(selector).forEach(e=>e.style.color=color)};set('#categories .section-head h2','categories_heading_color');set('#products .section-head h2','products_heading_color');set('#homeBrands .head h2','brands_heading_color');set('#why .section-head h2','why_heading_color');set('#aboutTitle','about_heading_color');set('#contact .section-head h2','contact_heading_color')}
function toggleSection(flag,id){const el=$(id);if(!el)return;const sec=el.closest('section');if(sec&&data[flag]===false)sec.style.display='none';else if(sec)sec.style.display='block'}
function renderHomeHero(){const host=$('slides');if(!host)return;const hs=(data.hero_images||[]).filter(x=>x&&x.show!==false);host.innerHTML=hs.map((s,i)=>`<div class="slide ${i===0?'active':''}"><img class="slide-bg" src="${esc(imageUrl(s.image))}" alt="">${s.show_overlay===true?`<div class="slide-shade" style="background:${esc(s.overlay_color||'#123b73')};opacity:${Math.max(0,Math.min(1,Number(s.overlay_opacity??.45)))}"></div>`:''}<div class="slide-content"><h1 style="color:${esc(s.heading_color||'var(--heroheadingcolor,#ffffff)')};font-family:${esc(s.heading_font||'var(--heroheadingfont)')};font-weight:${esc(s.heading_font_weight||'var(--heroheadingweight)')};font-style:${esc(s.heading_font_style||'var(--heroheadingstyle)')}">${esc(s.heading||'')}</h1><p style="color:${esc(s.text_color||'var(--herotextcolor,#ffffff)')};font-family:${esc(s.text_font||'var(--herotextfont)')};font-weight:${esc(s.text_font_weight||'var(--herotextweight)')};font-style:${esc(s.text_font_style||'var(--herotextstyle)')}">${esc(s.text||'')}</p><div class="actions">${s.show_button!==false&&s.button_text?`<a class="btn primary" href="${esc(s.button_link||'products.html')}">${esc(s.button_text)}</a>`:''}${s.show_second_button&&s.second_button_text?`<a class="btn secondary" href="${esc(s.second_button_link||'contact.html')}">${esc(s.second_button_text)}</a>`:''}</div></div></div>`).join('')+`<div class="dots">${hs.map((_,i)=>`<button class="dot ${i===0?'active':''}" data-slide="${i}"></button>`).join('')}</div>`;let n=0;const go=i=>{const ss=host.querySelectorAll('.slide'),ds=host.querySelectorAll('.dot');if(!ss.length)return;n=(i+ss.length)%ss.length;ss.forEach((s,j)=>s.classList.toggle('active',j===n));ds.forEach((d,j)=>d.classList.toggle('active',j===n))};host.querySelectorAll('.dot').forEach(d=>d.onclick=()=>go(+d.dataset.slide));clearInterval(window.slideTimer);window.slideTimer=hs.length>1?setInterval(()=>go(n+1),5000):null}
function renderHomeCategories(){const g=$('categoriesGrid');if(!g)return;const cats=(data.categories||[]).filter(c=>c&&c.show!==false&&c.name);g.innerHTML=cats.map(c=>`<a class="cat" href="products.html?category=${encodeURIComponent(c.name)}"><div class="cat-icon">${c.image?`<img src="${esc(imageUrl(c.image))}" alt="">`:(c.icon||'📚')}</div><h3>${esc(c.name)}</h3></a>`).join('')}
function productCard(p){return `<article class="prod"><div class="prodimg">${p.image?`<img src="${esc(imageUrl(p.image))}" alt="${esc(p.name||'')}">`:''}</div><div class="prodbody"><h3>${esc(p.name||'')}</h3>${p.brand?`<div class="prodbrand">${esc(p.brand)}</div>`:''}<p>${esc(p.description||'')}</p>${p.show_price&&p.price?`<div class="price">${esc(p.sale_price||p.price)}</div>`:''}<div class="actions"><a class="btn primary" href="products.html?category=${encodeURIComponent(p.category||'')}${p.brand?'&brand='+encodeURIComponent(p.brand):''}">View Products</a></div></div></article>`}
function renderHomeProducts(){const g=$('productsGrid');if(!g)return;g.innerHTML=(data.products||[]).filter(p=>p&&p.show!==false).slice(0,6).map(productCard).join('')}
function renderHomeBrands(){const host=$('homeBrands');if(!host)return;const brands=(data.brands||[]).filter(b=>b&&b.show!==false&&b.name);if(!brands.length){host.style.display='none';return}host.style.display='block';host.innerHTML=`<div class="container"><div class="head"><h2>${esc(data.brands_title||'Shop All Brands')}</h2><p>${esc(data.brands_subtitle||'Explore products by brand.')}</p></div><div class="grid brandgrid">${brands.slice(0,8).map(b=>`<a class="brand-card" href="products.html?brand=${encodeURIComponent(b.name)}"><div class="brand-logo">${b.logo?`<img src="${esc(imageUrl(b.logo))}" alt="${esc(b.name)}">`:'<span>BRAND</span>'}</div><h3>${esc(b.name)}</h3></a>`).join('')}</div><div style="text-align:center;margin-top:25px"><a class="btn primary" href="brands.html">${esc(data.brands_button_text||'Shop All Brands')}</a></div></div>`}
function renderHomeWhy(){const g=$('whyGrid');if(g)g.innerHTML=(data.why_choose_us||[]).filter(x=>x&&x.show!==false).map(x=>`<div class="why"><div class="why-icon">${esc(x.icon||'✓')}</div><h3>${esc(x.title||'')}</h3><p>${esc(x.description||x.text||'')}</p></div>`).join('')}
function renderHomeAbout(){const t=$('aboutText');if(t)t.innerHTML=String(data.about_text||data.about||'').replace(/\n/g,'<br>');const title=$('aboutTitle');if(title)title.textContent=data.about_title||'About Our Store'}
function renderCategories(){renderHomeCategories()}
function renderBrands(){const g=$('brandsGrid');if(!g)return;const brands=(data.brands||[]).filter(b=>b&&b.show!==false&&b.name);g.innerHTML=brands.map(b=>`<a class="brand-card" href="products.html?brand=${encodeURIComponent(b.name)}"><div class="brand-logo">${b.logo?`<img src="${esc(imageUrl(b.logo))}" alt="${esc(b.name)}">`:'<span>BRAND</span>'}</div><h3>${esc(b.name)}</h3>${b.description?`<p>${esc(b.description)}</p>`:''}</a>`).join('')||'<p>No brands added yet.</p>'}
function renderProducts(){const g=$('productsGrid');if(!g)return;const products=(data.products||[]).filter(p=>p&&p.show!==false);const params=new URLSearchParams(location.search);let cat=params.get('category')||'all',brand=params.get('brand')||'all',q='';const f=$('filters');const cats=['all',...new Set(products.map(p=>p.category).filter(Boolean))],brands=['all',...new Set(products.map(p=>p.brand).filter(Boolean))];if(f)f.innerHTML=`<div class="filter-group"><span>Category:</span>${cats.map(c=>`<button class="filter ${c.toLowerCase()===cat.toLowerCase()?'active':''}" data-cat="${esc(c)}">${esc(c==='all'?'All':c)}</button>`).join('')}</div><div class="filter-group"><span>Brand:</span>${brands.map(b=>`<button class="filter brandfilter ${b.toLowerCase()===brand.toLowerCase()?'active':''}" data-brand="${esc(b)}">${esc(b==='all'?'All':b)}</button>`).join('')}</div>`;const draw=()=>{const list=products.filter(p=>(cat==='all'||String(p.category||'').toLowerCase()===cat.toLowerCase())&&(brand==='all'||String(p.brand||'').toLowerCase()===brand.toLowerCase())&&(!q||JSON.stringify(p).toLowerCase().includes(q)));g.innerHTML=list.map(productCard).join('')||'<p>No products found.</p>'};f?.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;f.querySelectorAll('[data-cat]').forEach(x=>x.classList.remove('active'));b.classList.add('active');draw()});f?.querySelectorAll('[data-brand]').forEach(b=>b.onclick=()=>{brand=b.dataset.brand;f.querySelectorAll('[data-brand]').forEach(x=>x.classList.remove('active'));b.classList.add('active');draw()});$('search')?.addEventListener('input',e=>{q=e.target.value.toLowerCase();draw()});draw()}
function renderAbout(){renderHomeAbout();const box=$('aboutImage');if(box&&data.about_image)box.src=imageUrl(data.about_image)}
function renderGallery(){const g=$('galleryGrid');if(!g)return;g.innerHTML=(data.gallery||[]).filter(x=>x&&x.show!==false).map(x=>`<div class="gallery-item"><img src="${esc(imageUrl(x.image))}" alt="${esc(x.caption||'')}"><div>${esc(x.caption||'')}</div></div>`).join('')||'<p>No gallery photos added yet.</p>'}
function renderContact(){const map=$('map');if(map&&data.map_embed)map.src=data.map_embed;['address','phone','whatsapp','timings'].forEach(id=>{if($(id))$(id).textContent=data[id]||''});const c=$('callButton');if(c)c.href='tel:'+(data.phone||'');const w=$('waButton');if(w)w.href='https://wa.me/'+String(data.whatsapp||data.phone||'').replace(/\D/g,'')}
loadData();