const RAW='https://raw.githubusercontent.com/Holkarandasshemraj/Holkarandasshemraj.github.io/main/images/uploads/';
const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data={shop_name:'Holkaran Dass Hem Raj',tagline:'Learn. Create. Play. Celebrate.',logo:RAW+'file_00000000f9e48211ae9421db860baf41.png',categories:[],products:[],gallery:[],why_choose_us:[]};
async function loadData(){try{const r=await fetch('/content.yml?cache='+Date.now(),{cache:'no-store'});if(r.ok&&window.jsyaml)data=Object.assign(data,jsyaml.load(await r.text())||{});}catch(e){}applyTheme();renderHeader();renderPage();}
function applyTheme(){const m={primary_color:'--primary',secondary_color:'--secondary',accent_color:'--accent',background_color:'--bg',card_background_color:'--card',text_color:'--text',heading_color:'--heading',call_button_color:'--call',enquire_button_color:'--enquire',button_text_color:'--btntext',body_font:'--bodyfont',heading_font:'--headingfont',nav_font:'--navfont',button_font:'--buttonfont',product_font:'--productfont',body_font_weight:'--bodyweight',heading_font_weight:'--headingweight',nav_font_weight:'--navweight',button_font_weight:'--buttonweight',body_font_style:'--bodystyle',heading_font_style:'--headingstyle',nav_font_style:'--navstyle',button_font_style:'--buttonstyle',body_font_size:'--bodysize',heading_font_size:'--headingsize',button_font_size:'--buttonsize',product_font_size:'--productsize',product_description_font_size:'--productdescsize'};for(const k in m)if(data[k])document.documentElement.style.setProperty(m[k],data[k]);}
function renderHeader(){document.querySelectorAll('[data-shop-name]').forEach(e=>e.textContent=data.shop_name||'Holkaran Dass Hem Raj');document.querySelectorAll('[data-tagline]').forEach(e=>e.textContent=data.tagline||'');const logo=$('brandLogo');if(logo&&data.logo)logo.src=data.logo;buildDropdown();}
function buildDropdown(){const list=$('categoryMenu');if(!list)return;const cats=data.categories||[];list.innerHTML=cats.filter(c=>c&&c.show!==false).map(c=>`<a href="products.html?category=${encodeURIComponent(c.name||'')}">${esc(c.name||'Category')}</a>`).join('')||'<a href="products.html">All Products</a>';}
function setupNav(){const menu=$('menu'),nav=$('nav');if(menu)menu.onclick=()=>nav.classList.toggle('open');document.querySelectorAll('.dropdown-toggle').forEach(b=>b.onclick=e=>{if(innerWidth<=760){e.preventDefault();b.parentElement.classList.toggle('open')}});}
function renderPage(){const page=document.body.dataset.page||'home';if(page==='home')renderHome();if(page==='categories')renderCategories();if(page==='products')renderProducts();if(page==='about')renderAbout();if(page==='gallery')renderGallery();if(page==='contact')renderContact();setupNav();}
function imageUrl(v){if(!v)return '';if(/^https?:\/\//.test(v)||v.startsWith('/'))return v;return RAW+v.split('/').pop();}
function renderHome(){const slides=$('slides');const hs=(data.hero_images||[]).filter(x=>x&&x.show_slide!==false);if(slides){slides.innerHTML=hs.map((s,i)=>`<div class="slide ${i===0?'active':''}"><img class="slide-bg" src="${esc(imageUrl(s.image))}" onerror="this.style.display='none'" alt=""><div class="slide-shade" style="background:${esc(s.overlay_color||'#123b73')};opacity:${Number(s.overlay_opacity??.45)}"></div><div class="slide-content"><h1>${esc(s.heading||'')}</h1><p>${esc(s.text||'')}</p><div class="actions">${s.show_button!==false&&s.button_text?`<a class="btn primary" href="${esc(s.button_link||'products.html')}">${esc(s.button_text)}</a>`:''}${s.show_second_button&&s.second_button_text?`<a class="btn secondary" href="${esc(s.second_button_link||'contact.html')}">${esc(s.second_button_text)}</a>`:''}</div></div></div>`).join('')+`<div class="dots">${hs.map((_,i)=>`<button class="dot ${i===0?'active':''}" data-slide="${i}"></button>`).join('')}</div>`;let n=0;const go=i=>{const ss=slides.querySelectorAll('.slide'),ds=slides.querySelectorAll('.dot');if(!ss.length)return;n=(i+ss.length)%ss.length;ss.forEach((s,j)=>s.classList.toggle('active',j===n));ds.forEach((d,j)=>d.classList.toggle('active',j===n));};slides.querySelectorAll('.dot').forEach(d=>d.onclick=()=>go(+d.dataset.slide));clearInterval(window.slideTimer);window.slideTimer=setInterval(()=>go(n+1),5000);}
renderCategories();
function renderCategories(){const grid=$('categoriesGrid');if(!grid)return;const cats=(data.categories||[]).filter(c=>c&&c.show!==false);grid.innerHTML=cats.map(c=>`<a class="cat" href="products.html?category=${encodeURIComponent(c.name||'')}"><div class="cat-icon">${c.image?`<img src="${esc(imageUrl(c.image))}" alt="">`:(c.icon||'📚')}</div><h3>${esc(c.name||'')}</h3></a>`).join('');}
function renderProducts(){const grid=$('productsGrid');if(!grid)return;const products=(data.products||[]).filter(p=>p&&p.show!==false);const params=new URLSearchParams(location.search);let chosen=params.get('category')||'all';const filters=$('filters');const cats=['all',...new Set(products.map(p=>p.category).filter(Boolean))];if(filters)filters.innerHTML=cats.map(c=>`<button class="filter ${c.toLowerCase()===chosen.toLowerCase()?'active':''}" data-cat="${esc(c)}">${esc(c==='all'?'All':c)}</button>`).join('');let q='';const draw=()=>{const list=products.filter(p=>(chosen==='all'||String(p.category||'').toLowerCase()===chosen.toLowerCase())&&(!q||JSON.stringify(p).toLowerCase().includes(q)));grid.innerHTML=list.map(p=>`<article class="prod"><div class="prodimg">${p.image?`<img src="${esc(imageUrl(p.image))}" alt="${esc(p.name||'')}">`:''}</div><div class="prodbody"><h3>${esc(p.name||'')}</h3><p>${esc(p.description||'')}</p>${p.show_price&&p.price?`<div class="price">${esc(p.sale_price||p.price)}</div>`:''}<div class="actions">${p.show_call!==false?`<a class="btn primary" href="tel:${esc(data.phone||'')}">Call</a>`:''}${p.show_enquire!==false?`<a class="btn" style="background:var(--enquire);color:#fff" href="https://wa.me/${String(data.whatsapp||data.phone||'').replace(/\D/g,'')}">Enquire</a>`:''}</div></div></article>`).join('')||'<p>No products found.</p>';};filters?.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{chosen=b.dataset.cat;filters.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');draw()});$('search')?.addEventListener('input',e=>{q=e.target.value.toLowerCase();draw()});draw();}
function renderAbout(){const t=$('aboutText');if(t)t.innerHTML=String(data.about_text||'').replace(/\n/g,'<br>');const title=$('aboutTitle');if(title)title.textContent=data.about_title||'About Our Store';const img=$('aboutImage');if(img&&data.about_image)img.src=imageUrl(data.about_image);}
function renderGallery(){const g=$('galleryGrid');if(!g)return;g.innerHTML=(data.gallery||[]).filter(x=>x&&x.show!==false).map(x=>`<div class="gallery-item"><img src="${esc(imageUrl(x.image))}" alt="${esc(x.caption||'')}"></div>`).join('');}
function renderContact(){const map=$('map');if(map&&data.map_embed)map.src=data.map_embed;for(const id of ['address','phone','whatsapp'])if($(id))$(id).textContent=data[id]||'';const c=$('callButton');if(c)c.href='tel:'+(data.phone||'');const w=$('waButton');if(w)w.href='https://wa.me/'+String(data.whatsapp||data.phone||'').replace(/\D/g,'');}
loadData();